### ISSUE TITLE
Как вообще работают настройки?

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-lite-youtube-embed#11]
Выключаю создание микроразметки, но при этом ничего не меняется. Сбрасываю кеш ембедов отваливаются посты с видосами с ошибкой ERR_CONNECTION_RESET. Но если создать новый пост с виддосом то на настройки реагирует.

**Comment by artikus11** [comment]
Такое поведение кеша наблюдаю только на локалке, на боевом все ровно. Хотя надо еще потестить

**Comment by mihdan** [comment]
Какой вебсервер локально?

**Comment by artikus11** [comment]
Ларагон

**Comment by artikus11** [comment]
Попробовал развернуть другой проект, такой проблемы нет. Все ровно и кеш сбрасывается и выводиться. 

Словил баг на теме OceanWP 
![image](https://user-images.githubusercontent.com/16116688/88116138-eee36880-cbc8-11ea-9203-b63856f14e62.png)
тема свои обертки добавляет и из-за этого красная кнопка улетает
