### ISSUE TITLE
не понял как работает настройка размер плеера

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-lite-youtube-embed#12]
у меня она никак не работает, вообще не реагирует на эту настройку. Что есть она что  нет, один фиг на всю ширину растягивается. или я не понял как эта настройка вообще должна работать

**Comment by mihdan** [comment]
@artikus11 проверь-ка

**Comment by artikus11** [comment]
@mihdan а апдей-то в репе уже?

**Comment by artikus11** [comment]
А все вижу, ща проверю

**Comment by artikus11** [comment]
Ага, теперь работает. Правда пришлось статьи с установленными видосами пересохранить, но работает. @mihdan

**Comment by mihdan** [comment]
Нужно понять что делать с кешем и когда его скиндывать. Это тут https://github.com/mihdan/mihdan-lite-youtube-embed/issues/11

**Comment by artikus11** [comment]
Изменил размер. Варнинг выпал 
![image](https://user-images.githubusercontent.com/16116688/88114657-6d3e0b80-cbc5-11ea-9d9a-2b8274cc7769.png)
Это при первом обновлении страницы, потом уходит.

Но такие жесткие размеры - это не есть правильно, они не адаптивными становятся. Делаешь размер 1280x720 и все начинает вылезать за границу. Стили тогда надо какие то прикручивать для элемента `lite-youtube`, чтобы масштабировалось. А еще размеры стайлом добавляются, вообще атас.

**Comment by mihdan** [comment]
Нужно добавить два пункта: 16 на 9 адаптив и 4 на 3 адаптив, а размеры эти из стандартных размеров их апи, тут кому как надо

**Comment by artikus11** [comment]
Да, так даже удобнее будет
