### ISSUE TITLE
Дефолтное описание разметки

### ISSUE THREAD

**Issue by artikus11** [mihdan/mihdan-lite-youtube-embed#17]
Бывает так, что в видосах нет описания, имеет смысл какое-то дефолтное подтягивать. Например из настроек, так как на статье то же может не быть описания, просто видос добавлен.

**Comment by mihdan** [comment]
У тебя есть страницы, где нет вообще никакого текста?

**Comment by artikus11** [comment]
Сам был в шоке, но действительно такая страница нашлась) Хотя нет, что-то в две строки действительно есть, так что можно по дефолту с записи брать
