### ISSUE TITLE
Инструкцию пошаговую вплоть до API Youtube

### ISSUE THREAD

**Issue by Feelosov** [mihdan/mihdan-lite-youtube-embed#18]
Все в сабже. У меня плагин не заработал, потому что видимо, что-то делал не как задумано.

**Comment by Feelosov** [comment]
Хотя сейчас обновил (была версия 1.4.4) и плагин правильно работает, а может надо было подождать апдейта от Youtube, но в любом случае, хорошая инструкция не помешает.

**Comment by mihdan** [comment]
Была проблема с кешем, сейчас ее исправили, инструкцию напишем, можете почоь при желании.

**Comment by Feelosov** [comment]
Сами напишите? 
2-3 августа могу приступить, если нет спешки. Чтобы подсобрать обратную связь.
Полагаю, в эти же дни и управлюсь.

Для согласования с разработчиком и дополнения другими пользователями:

1. Инструкцию на русском в текстовом виде с сопровождением картинок.
2. Описать момент установки из репозитория.
3. Описать где в админке настройки плагина, какая настройка за что отвечает (тесты, контакт с разработчиком).
4. Описать создание учетных данных и API в консоли google, как если бы пользователь первый раз об этом слышал.
5. Скриншоты с тестового поддомена или локалки, с тестового аккаунта google.
6. Получить технические требования от разработчика (минимальные библиотеки, версия php, включенные куки и т.д.).
7. Описать распространенные ошибки пользователей, потенциальные проблемы.
8. В виде word, pdf или сразу статьи в WordPress.
9. Описать полезные советы общего плана по встраиванию видео в качестве комплемента от разработчика, например, рекомендуемое число вставок, оптимальные настройки, подбор заглушки (своей картинки-превью - есть же такое?), прочее.
10. ...

Дополняйте, коллеги. Может быть кто-то уже сталкивался с проблемами, которые стоило бы включить в инструкцию.

**Comment by mihdan** [comment]
Можно добавить в плагин Help Tab

**Comment by mihdan** [comment]
https://www.kobzarev.com/projects/lite-youtube-embed/
