### ISSUE TITLE
Конверт старых вставок

### ISSUE THREAD

**Issue by artikus11** [mihdan/mihdan-lite-youtube-embed#24]
Вот это прям проблема. Если на сайте 1000 записей и каждой по 1-2 видоса, то перевставлять каждое видео так еще задачка. Какой-то конвертор нужен, что уже вставленные видео конвертировал в формат lite-frame

**Comment by mihdan** [comment]
Так кеш же почисть в инструментах)

**Comment by artikus11** [comment]
да чистил вроде, но надо проверить, мог и забыть

**Comment by mihdan** [comment]
Сейчас кнопка очистки кеша - убивает и старый кеш тож, при первом ображении к такой странице кеш уже создается с новой версткой
