### ISSUE TITLE
Автозапуск на мобилках

### ISSUE THREAD

**Issue by artikus11** [mihdan/mihdan-lite-youtube-embed#25]
На мобилках приходится дважды на плеер нажимать. Так и положено или можно с этим что-то сделать?

**Comment by mihdan** [comment]
Если это не работает из корорбки, то без подключения jsapi разрулить не выйдет, это где-то работает?

**Comment by artikus11** [comment]
Тестил у себя на телефоне, приходится дважды тыкать. А так хз, не встречал чтобы по другому работало, это видимо сам плеер ютуба так отрабатывает

**Comment by mihdan** [comment]
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes ничего не поможет уже)

**Comment by mihdan** [comment]
На десктопе работает почти везде если замьютить при помощи `?mute=1`

**Comment by artikus11** [comment]
Ну и фиг с ним тогда, закрывай ишук)

**Comment by mihdan** [comment]
Попробовать https://stackoverflow.com/a/31433210/2050648

**Comment by mihdan** [comment]
По дефолту видео замьютил
