### ISSUE TITLE
Поменять местами параметры "Description" и "Использовать микроразметку"

### ISSUE THREAD

**Issue by Feelosov** [mihdan/mihdan-lite-youtube-embed#26]
Поскольку поле Description работает в контексте микроразметки, то логичнее, мне кажется, поставить параметр "Использовать микроразметку" до параметра "Description".
![2020-08-03_19-53-12](https://user-images.githubusercontent.com/28943203/89179866-31db0e00-d5c3-11ea-8f2e-8b1e4a2a6fdb.png)

Кстати, тут же я бы дополнил описание параметра "Description", что он предназначен для itemprop="description" и то, что этот параметр актуален только если ключ API не используется. По последнему: или сделать так, чтобы параметр "Description" перезаписывал подгружаемую информацию.

**Comment by mihdan** [comment]
@Feelosov микроразметка работает и без ключа!
