### ISSUE TITLE
Параметры плеера

### ISSUE THREAD

**Issue by seojacky** [mihdan/mihdan-lite-youtube-embed#38]
Просто для информации, для того чтобы задать начальное время воспроизведения ролика используются 2 альтернативных способа:
```
https://www.youtube.com/watch?v=EVltAuF9iZI&t=26s
https://www.youtube.com/watch?v=EVltAuF9iZI&start=26s
```
В обоих случая воспроизведение начнется с 26 секунды

**Comment by mihdan** [comment]
У меня передаются все параметры
