### ISSUE TITLE
Чекать видео на Ютубе, а не удалено ли, не заблокировано ли и отправлять уведомление.

### ISSUE THREAD

**Issue by Feelosov** [mihdan/mihdan-lite-youtube-embed#43]
Вот это точно будет бомбическая правка, потому что статейники с 50+ статьями и у всех видео не проверишь каждый раз, актуально оно или нет. При этом, когда пользователь заходит и видео не видит, то сайт сразу теряет свой внешний вид, иногда свою ценность.

Если увидел твой скрипт, что видео на сервисе удалено, заблокировано, скрыто, то сообщать владельцу сайта на мейл (или контент-менеджеру - то есть дать поле, чтобы сами указывали получателя) однократно или раз в неделю, что видео не актуально. 

Ориентировать можно по классам или тегам содержащим "error" или просто за наличие id="reason" - если парсить.

Эту фичу можно в платную ПРО загнать, вообще.

**Comment by mihdan** [comment]
Смысл плагина был в том что он реактивный, маленький и простой, а тут нужен крон, который постоянно будет ролики перепроверять, как-то сообщать про это админу, крон может не работать на сервере, почта тоже быть поломанной, смс платно, пуши заблочены))) Если только для про-версии. Можете проспонсировать - сделаем

**Comment by Feelosov** [comment]
1. Я бы проспонсировал, но мне это не надо и денег нету.
2. Не нужен крон. С кроном будет бедлам. Нужно проверять при запросе страницы, как это сейчас.

**Comment by mihdan** [comment]
1. Тогда, скорее всего, это так и останется в идеях)
2. Если бы проверки происходили при каждом запросе страницы - меня бы распяли давно. Запрос формируется один раз при вставке видео в админке WP, потом полученный код кэшируется. Сбросить кэш можно в настройках плагина. После сброса кэша запрос формируется опять же один раз при посещении страницы или при редактировании данной записи в админке. Никто в здравом уме не будет открывать внешние соединения просто так.

**Comment by Feelosov** [comment]
2. Ой, боже мой, зачем я это сказал. Надо развидеть: чик (c) MiB. Запарился, о чем-то своем думал.

У меня раньше был контентный сайт и, я думаю, проверки даже раз в месяц хватило бы. Каждый 10-й видеоролик исчезал.

**Comment by seojacky** [comment]
> 2. Ой, боже мой, зачем я это сказал. Надо развидеть: чик (c) MiB. Запарился, о чем-то своем думал.
> 
> У меня раньше был контентный сайт и, я думаю, проверки даже раз в месяц хватило бы. Каждый 10-й видеоролик исчезал.

Установи плагин Broken link checker и будет тебе счастье

**Comment by Feelosov** [comment]
> > 2. Ой, боже мой, зачем я это сказал. Надо развидеть: чик (c) MiB. Запарился, о чем-то своем думал.
> > 
> > У меня раньше был контентный сайт и, я думаю, проверки даже раз в месяц хватило бы. Каждый 10-й видеоролик исчезал.
> 
> Установи плагин Broken link checker и будет тебе счастье

Мне вообще-то не нужно.
