### ISSUE TITLE
Не обрабатывает iframe в постах

### ISSUE THREAD

**Issue by seojacky** [mihdan/mihdan-lite-youtube-embed#45]
Две проблемы:
1. Не обрабатывает iframe в постах `<iframe width="1730" height="685" src="https://www.youtube.com/embed/OvHB-rSHOXU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>`
2. Даже если вставлю в пост просто ссылкой - тоже не так как надо. Выставляю самые разные размеры в настройках - всё равно размеры превью и видео не на всю ширину поста.
Пример https://stage.vskali.ru/articles/mir/otkrytie-strany-evropy-dlya-rossiyan/

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-lite-youtube-embed/commit/8252af396d730207d38b95c702a885a4efa86148
